
include:
  - board: akdk_nrf52840
    shield: unsplitball
    snippet: studio-rpc-usb-uart
    artificial-name: unsplitball
  - board: akdk_nrf52840
    shield: settings_reset
    artificial-name: settings_reset
